[package]
name = "zebot"
version = "0.1.0"
authors = ["Marcus Borkenhagen <m@fritschy.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "6.0"
smol = "1.2"
clap = "2.33"
select = "0.5"

[dependencies.reqwest]
version = "0.10"
features = [ "blocking" ]

[profile.release]
lto = true
codegen-units = 1
