[package]
name = "zebot"
version = "0.1.0"
authors = ["Marcus Borkenhagen <m@fritschy.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = { version = "6.0", features = [ "lexical" ] }
tokio = { version = "1.0", features = [ "full" ] }
futures-util = "*"
clap = "2.33"
select = "0.5"
humantime = "2.0.1"
rand = "*"

[profile.release]
#debug = true
#lto = true
#codegen-units = 1
