[package]
name = "irc2"
version = "0.1.0"
authors = ["Marcus Borkenhagen <m@fritschy.de>"]
edition = "2018"

[dependencies]
nom = "7.0"
tracing = "0.1"

[profile.release]
#debug = true
lto = true
codegen-units = 1

[profile.test]
debug = true
opt-level = 0
