#!/usr/bin/env python3

from bs4 import BeautifulSoup
from urllib.request import urlopen

from handler_lib import *

lines = []
qid = ""

try:
    with urlopen("http://german-bash.org/action/random") as r:
        bs = BeautifulSoup(r.read(), features="lxml")
    qb = bs.find(attrs={"class": "quotebox"})
    qid = next((x.attrs['name'] for x in qb.children if x.name))
    quote = bs.find('div', {'class': 'zitat'})
    lines = list(filter(lambda x: x!='', map(str.strip, quote.strings)))
except:
    log({"exc_info": sys.exc_info()})
    handler_exit(0, lines=["Uhm, did not recognize the HTML ..."], box=0)

handler_exit(0, lines=lines, box=1, title=qid, wrap_single_lines=1)
