#!/usr/bin/env python3

import json
import re
import sys
import time
from subprocess import run, PIPE

def output_lines(output):
    return list(map(lambda x: x.strip(), output.decode().splitlines()))

if len(sys.argv) < 3:
    print(json.dumps({"error": "not enough arguments to handler"}))
    sys.exit(1)

# argv: ["./fortune", "src@irc-user|channel", "!fortune -args"]
args = list(re.split(r'\s+', sys.argv[2]))

# skip the !command
args = args[1:] if len(args) > 1 else []

command = ['fortune', *args]

retries = 6
while retries > 0:
    retries -= 1

    f = run(command, stdout=PIPE, stderr=PIPE)

    if f.returncode == 0:
        lines = output_lines(f.stdout)

        if len(lines) == 0:
            lines = output_lines(f.stderr)

        if len(lines) > 9:
            time.sleep(0.1)
            continue

        print(json.dumps({"lines": lines,
                          "box": 1,
                          "command": command}))
        sys.exit(0)
    else:
        print(json.dumps({"error": f.stderr.decode(),
                          "code": f.returncode,
                          "command": command}))
        sys.exit(1)

print(json.dumps({"error": "Could not get short-enough output"}))
sys.exit(1)
