#!/usr/bin/env python3

import json
import re
import sys
import time
from subprocess import run, PIPE

from handler_lib import *

def output_lines(output):
    return list(map(lambda x: x.strip(), output.decode().splitlines()))

command = ['fortune', *get_split_args()]
f = run(command, stdout=PIPE, stderr=PIPE)
if f.returncode == 0:
    lines = output_lines(f.stdout)
    if len(lines) == 0:
        lines = output_lines(f.stderr)
    handler_exit(0, lines=lines, box=1, command=command)
else:
    handler_exit(1, error=f.stderr.decode(), code=f.returncode, command=command)
