#!/usr/bin/env python3

import json
import re
import sys
import time
from subprocess import run, PIPE

args = list(re.split(r'\s+', sys.argv[2]))
if len(args) > 1:
    args = args[1:]
else:
    args = []

command = ['fortune', *args]

while 1:
    f = run(command, stdout=PIPE, stderr=PIPE)

    if f.returncode == 0:
        output = f.stdout
        lines = list(map(lambda x: x.strip(), output.decode().splitlines()))

        if len(lines) > 9:
            time.sleep(0.1)
            continue

        print(json.dumps({"lines": lines,
                          "box": 1,
                          "command": command}))
        break
    else:
        print(json.dumps({"error": f.stderr.decode(),
                          "code": f.returncode,
                          "command": command}))
        break
