#!/usr/bin/env python3

from urllib.request import urlopen, quote as urlquote
import json
import sys
import re

if len(sys.argv) < 3:
    print(json.dumps({"error": "not enough arguments to handler"}))
    sys.exit(1)

# argv: ["./fortune", "src@irc-user|channel", "!fortune -args"]
args = list(re.split(r'\s+', sys.argv[2]))

# skip the !command
args = args[1:] if len(args) > 1 else []

if len(args) < 1 or len(args[0]) == 0:
    print(json.dumps({"error": "not enough arguments to handler"}))
    sys.exit(1)

term = urlquote(" ".join(args))

with urlopen("https://api.duckduckgo.com/?q={}&format=json&pretty=0".format(term)) as r:
    response = json.loads(r.read())

topics = response.get("RelatedTopics", [])

if len(topics) > 0:
    print(json.dumps({"wrap": 1, "lines": [topics[0]['Text'], "        -- " + topics[0]['FirstURL']], "box": 1}))
else:
    print(json.dumps({"lines": ["no result from search, try https://duckduckgo.com/?q={}".format(term)],
                      "argv": sys.argv}))
