#!/usr/bin/env python3

from handler_lib import *
from urllib.request import urlopen, quote as urlquote
from bs4 import BeautifulSoup as BS

args = urlquote(get_args())
url = "https://www.urbandictionary.com/define.php?term={}".format(args)
with urlopen(url) as r:
    bs=BS(r.read())

title = bs.find("div", attrs={"class": "def-header"}).text
lines = [bs.find("div", attrs={"class": "meaning"}).text, "        -- {}".format(url)]

handler_exit(0, lines=lines, title=title, box=1, wrap_single_lines=1)
