#!/usr/bin/env python3

from handler_lib import handler_exit, get_args, get_from, get_to
import errno
import os
import re

args = get_args()
nick = get_from()
channel = get_to()

with open("rw_data/urls.txt") as f:
    if len(args) < 1:
        lines = list(filter(lambda x: x[1] == channel, map(lambda x: x.strip().split("\t"), f.readlines())))
        if len(lines) > 0:
            time, chan, nick, url = lines[-1]
            handler_exit(0, lines=["Last URL from {}: {}".format(nick, url)])
        else:
            pass
    else:
        lines = list(filter(lambda x: x[1] == channel and re.match(args[1], x[3]), map(lambda x: x.strip().split("\t"), f.readlines())))
        if len(lines) > 4:
            lines = lines[-4:]
        lines = list(map(lambda x: x[3], lines))
        handler_exit(0, lines=lines)